PR: improving macro with adding attributes properties for struct
douggynix/dto_mapper pull request #11
Opened 2024-10-15 17:00 UTC by fatihaziz

Here my update regarding to support:
1. Override generated attribute macro for Struct
2. Handle attribute macro for _new fields_

Thank you, best regard

2024-10-16 17:13 UTC, douggynix commented
By the way, what type of code formatter are you using? i think you're using a special code formatting settings in your IDE that changes all of the source code files formatting. I was using cargo default code formatter. 
```shell
cargo fmt --verbose
```

2024-10-16 18:17 UTC, douggynix requested changes
Thanks for your contribution for the macro attributes per mapper entry field that targets generated structs :).

All of the other changes look good to me. just submit those requested changes in the comments and I'll go on after that to merge the PR.

I'll open up another PR as well after that to proceed with "field attribute" macro as you already lay the foundation codes to parse and generate macro attributes.

2024-10-16 19:10 UTC, fatihaziz commented
> By the way, what type of code formatter are you using? i think you're using a special code formatting settings in your IDE that changes all of the source code files formatting. I was using cargo default code formatter.
> 
> ```shell
> cargo fmt --verbose
> ```

yes i use the same,, just i put wordwrap 100 here so it might different from yours

2024-10-16 19:12 UTC, fatihaziz commented
> Thanks for your contribution for the macro attributes per mapper entry field that targets generated structs :).
> 
> All of the other changes look good to me. just submit those requested changes in the comments and I'll go on after that to merge the PR.
> 
> Do you consider to proceed as well with "field attribute" macros as you already lay the foundation codes to parse and generate macro attributes.
> 
> if so, the field attributes should be part of the map attribute such as the variants would look like this as before:
> 
> ```rust
> // the order of the elements in the tuple doesn't matter, only the type matters as they're different.
> We have a String Literal type, a Boolean literal type, and an Array of Literal type for the macro attributes
> map=([   
>      ( "field1:fieldA",  true,  [ "attrA", "attrB" ] ) ,  ( "field3:fieldB", [ "attrE" ] ),  ( "field2", [ "attrC", "AttrD" ] ), 
>  ])
> ```

i love to also adding that functionality on the _map_ attribute also, let me check it

2024-10-16 19:12 UTC, fatihaziz commented on examples/dto_example.rs
> +  new_fields=[( "name: String", "concat_str( self.firstname.as_str(), self.lastname.as_str() )" )]
sure will add that also

2024-10-16 19:56 UTC, douggynix commented
> > Thanks for your contribution for the macro attributes per mapper entry field that targets generated structs :).
> > All of the other changes look good to me. just submit those requested changes in the comments and I'll go on after that to merge the PR.
> > Do you consider to proceed as well with "field attribute" macros as you already lay the foundation codes to parse and generate macro attributes.
> > if so, the field attributes should be part of the map attribute such as the variants would look like this as before:
> > ```rust
> > // the order of the elements in the tuple doesn't matter, only the type matters as they're different.
> > We have a String Literal type, a Boolean literal type, and an Array of Literal type for the macro attributes
> > map=([   
> >      ( "field1:fieldA",  true,  [ "attrA", "attrB" ] ) ,  ( "field3:fieldB", [ "attrE" ] ),  ( "field2", [ "attrC", "AttrD" ] ), 
> >  ])
> > ```
> 
> i love to also adding that functionality on the _map_ attribute also, let me check it

Yeah, it would be a great idea doing it in the map. I already have codes that parse the Boolean and the "String Literal", you can just add another if case that parses the attributes here:

2024-10-16 19:58 UTC, douggynix commented
> > By the way, what type of code formatter are you using? i think you're using a special code formatting settings in your IDE that changes all of the source code files formatting. I was using cargo default code formatter.
> > ```shell
> > cargo fmt --verbose
> > ```
> 
> yes i use the same,, just i put wordwrap 100 here so it might different from yours, i will disable it for this project only, dont worry

Please, you can disable it so that we can ease code review and eliminates noise for formatting.
Thanks

2024-10-16 22:04 UTC, douggynix requested changes

2024-10-16 22:04 UTC, douggynix commented on tests/test_dto_creation.rs
> +    macro_attr=["serde(rename_all = \"UPPERCASE\")"]
if we can have macro attributes for existing fields as well with the use of map keyword already in use.

2024-10-16 22:37 UTC, douggynix requested changes

2024-10-16 22:37 UTC, douggynix commented on src/mapper_entry.rs
> +              Self::insert_next_field_value(
Could you replace this line by this one for code readability please:
```rust
              let new_field_attr = match attributes.is_empty(){
                true => None,
                false => Some(attributes.clone())
              };
              
              Self::insert_next_field_value(
                &mut vec_tuple,
                field_value.clone(),
                field_decl,
                &colon_position,
                new_field_attr
              );
```

2024-11-02 02:29 UTC, douggynix commented
Any update on this PR. Or could I provide any coding help with my suggestions above. 
Thanks

2024-11-16 02:41 UTC, douggynix commented
@fatihaziz As I have no feedback from you for the code review. I am going to merge the code onto the main branch and proceed with adding the changes highlighted in the review. I will open up another PR after merge so that you can see the related changes added.

Thanks a lot for your help and contribution to this code base.

2024-11-16 02:41 UTC, merged

2024-11-25 20:19 UTC, fatihaziz commented
@douggynix I'm very you don't hear update from free, i got very busy on my job.
thank you for your work, its work like i imagine!